### ISSUE TITLE
Exclude certain tests from mocha

### ISSUE THREAD

**Issue by JohnieLee** [rutgersmobile/arc-unit-mocha#1]
Is it possible to exclude certain tests from being run by mocha?  I have certain heavyweight integration tests that I want to exclude from `arc unit` tests.

**Comment by mr** [comment]
Currently we just run the `mocha` binary in `./node_modules` and parse the xunit output. Arcanist itself doesn't really know which files are being run right now. I'm not the most savvy mocha user, so I'm not sure if mocha can exclude tests with a config file or something, but if that's the case then it will probably "just work". If not, you can always add options to the call here: https://github.com/rutgersmobile/arc-unit-mocha/blob/master/src/engine/MochaEngine.php#L26

**Comment by mr** [comment]
Fixed by #2
